name: Blog-platter Gatekeeper

on:
  push:
    branches: [main]
  pull_request:
    branches: "*"

jobs:
  sast:
    name: Static Code Analysis (Semgrep + Bandit)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install semgrep bandit

      - name: Run Semgrep (secure code patterns)
        run: semgrep --config auto .

      - name: Run Bandit (Python security)
        run: bandit -r .
        continue-on-error: true

  dependencies:
    name: Dependency audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pip-audit
        run: |
          pip install pip-audit

      - name: Run pip-audit
        run: pip-audit